### ISSUE TITLE
Specification checklist

### ISSUE THREAD

**Issue by nocduro** [hammadj/Qwik-e-Classifier#11]
Check these off when they are ready to be submitted

* [x] Title page
* [x] Declaration of original content
* [x] Abstract
* [x] Table of contents
* [x] Functional Requirements
* [x] Design Alternatives
* [x] Design and Description of Operation #7 
* [x] Hardware requirements #8 
* [x] Parts list #5 
* [x] Available Source #12 
* [x] IO Signals #4 
* [x] Background research
* [x] Software design
* [x] Test plan
* [x] Results of experiments and characterization
* [x] Safety
* [x] Regulatory and Society
* [x] Schedule #1 
* [x] References #9 

## Appendices
* [x] Hardware documentation
* [x] Source code
* [x] Consent form #10
