### ISSUE TITLE
Progress Report checklist

### ISSUE THREAD

**Issue by nocduro** [hammadj/Qwik-e-Classifier#16]
* [x] more declaration of original content:
  * [x] linux
  * [x] tools
* [x] add CPU speed to HW requirements
* [x] add more IO stuff from Comments
* [x] how does NN work? (refer to software design section?)
* [ ] 8 new items in schedule
* [x] use vector diagram for hardware
* [x] add new code
* [x] HDMI IO signals

## Stuff to "upgrade" from last report
* [x] Functional Requirements
* [x] Design and Operation
* [x] convert Parts list to Bill of Materials
* [x] sign a new declaration of original content
* [x] More technical depth

## Stuff to add
* [x] sustainability
* [x] Performance measurement (already have this?)
* [x] other results of experiments and characterization (already have this?)
* [x] Annotate old schedule

**Comment by nocduro** [comment]
I've added 2 more things for myself on the schedule. If you guys can annotate your stuff in the old one, and add 2 more each for the new one?
